services:

  vault-server:
    build:
      context: ./server/
      args:
        VAULT_VERSION: ${VAULT_VERSION:-latest}
    hostname: vault-server
    environment:
      TZ: Europe/Madrid
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK

  vault-client:
    build:
      context: ./client/
      args:
        DEBIAN_VERSION: ${DEBIAN_VERSION:-latest}
    hostname: vault-client
    environment:
      VAULT_ADDR: "http://vault-server:8200"
      TZ: Europe/Madrid
    volumes:
      - user_data:/root

volumes:
  user_data:

networks:
  default:
    name: ${NETWORK_NAME}
